plugins {
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.app'
    id 'maven-publish'
}

dependencies {
    include xplibs.admin
    include xplibs.cluster
    include xplibs.content
    include xplibs.context
    include xplibs.export
    include xplibs.mail
    include xplibs.portal
    include xplibs.project
    include xplibs.task

    include libs.lib.landingpage
    include libs.lib.menu
    include libs.lib.thymeleaf
    include libs.lib.urlredirect

    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.2'
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev')
}

test {
    useJUnitPlatform()
}

xp {
    scriptEngines = ['Nashorn', 'GraalJS']
}
